// ⚠️ GENERATED FILE — regenerated by scripts/build.js on every build.
// Source of truth: apps/market-web/.env (overrides) + wrangler.toml [vars].

// PR 3 — closes MW-FE-008 (DPO email in bundle).
// DPO_EMAIL is NO LONGER bundled. Use getDpoContactUrl() instead —
// resolved at runtime via /api/legal/dpo-contact endpoint (CSP-allowed
// same-origin only). The endpoint is owned by the backend so it can
// rotate the underlying contact (form URL, alias, etc.) without rebuilding.
export function getDpoContactUrl(): string {
  // Same-origin endpoint — served by Astro backend, returns the current
  // DPO contact URL (rotated in env, never bundled).
  return "/api/legal/dpo-contact";
}

export const PTD_RAZON_SOCIAL = "Opita Code";
export const PTD_NIT = "1007465784";
export const PTD_DIRECCION = "Neiva, Huila, Colombia";
export const PTD_REP_LEGAL = "Representante Legal de Opita Code";
export const PTD_EMAIL_PUBLICO = "Owner@opitacode.com";
export const PTD_DPO_EMAIL = "nicourrutia83@gmail.com";
export const PTD_TELEFONO = "+57 312 6126085";
export const PUBLIC_PTD_TELEFONO = "+57 312 6126085";
